<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LoginIf you have a sahayya.com email ID_96077d</name>
   <tag></tag>
   <elementGuidId>81bb60dd-fa7b-41c3-840e-a08e09aa2a53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.justify-center.relative.h-screen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0930a4a9-0fa6-4fea-b739-fa55548df7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-center relative h-screen</value>
      <webElementGuid>058bff54-ac41-4044-aad4-6211c9de7903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LoginIf you have a sahayya.com email ID, Log in with GoogleLog in with GoogleORIf you are a partner or do not have a sahayya.com email ID, Log in with your registered email ID and passwordEmail IDPasswordMandatoryForgot PasswordLog in</value>
      <webElementGuid>faa85dc2-6cc2-4b36-b7bd-94c0eb98b87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex justify-center relative h-screen&quot;]</value>
      <webElementGuid>31feb810-204e-4573-b41f-f10a4e4d0f5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]</value>
      <webElementGuid>68289a2f-050b-4add-8ed5-62d3a1bcd3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>e789c0cf-1c23-4a9d-95fd-f49c3ba65d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LoginIf you have a sahayya.com email ID, Log in with GoogleLog in with GoogleORIf you are a partner or do not have a sahayya.com email ID, Log in with your registered email ID and passwordEmail IDPasswordMandatoryForgot PasswordLog in' or . = 'LoginIf you have a sahayya.com email ID, Log in with GoogleLog in with GoogleORIf you are a partner or do not have a sahayya.com email ID, Log in with your registered email ID and passwordEmail IDPasswordMandatoryForgot PasswordLog in')]</value>
      <webElementGuid>7ebc8cfe-7583-470e-8013-5153a8eab371</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
