<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>7a087af2-9750-45f3-8b6f-dcc24d53bde6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_63_content']/div/div[4]/div[2]/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;save&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ee2113a5-5503-4d81-95e1-980dac0631e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/Save_Image-8e728893.svg</value>
      <webElementGuid>f0731aa9-d43d-4e43-a56c-341dd72cbcf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>817bcb43-3675-44fa-91e7-28630e5bd2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_63_content&quot;)/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;self-center py-3 flex gap-5&quot;]/div[@class=&quot;flex flex-col text-xs items-center justify-center&quot;]/span[@class=&quot;w-12 h-12 cursor-pointer&quot;]/img[1]</value>
      <webElementGuid>e8d277d4-1f83-4a5d-bb92-113fadf130c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_63_content']/div/div[4]/div[2]/span/img</value>
      <webElementGuid>6f2e0aae-afc7-4b3a-864b-71bce977c756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='save']</value>
      <webElementGuid>6e289f11-94d5-47ec-98df-25e274b33990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/img</value>
      <webElementGuid>80d32368-10b2-43f8-88e4-fd4de752f23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/Save_Image-8e728893.svg' and @alt = 'save']</value>
      <webElementGuid>4e00b3ce-8e6a-42c3-89fe-9559f14cf6f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
