<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>d821d8ea-fc51-43a1-9a64-867c2504c336</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/assets/Add-09ceabbe.svg' and @alt = 'add-file']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;add-file&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[2]/div[2]/div/div/div/div[3]/div[2]/div/div/div/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>643f0fa1-cd9f-426f-b2ed-dacf8e4e4d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/Add-09ceabbe.svg</value>
      <webElementGuid>2677aa61-770b-4f67-b3b1-4d95558a1e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>add-file</value>
      <webElementGuid>bad220bf-ff25-4848-a565-e3a153189241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-full flex overflow-hidden bg-primary-sapphireBlue-100&quot;]/div[@class=&quot;bg-primary-sapphireBlue-100 max-w-328 m-auto flex-1 h-screen overflow-hidden p-3&quot;]/main[@class=&quot;overflow-auto&quot;]/div[1]/div[@class=&quot;flex flex-col gap-5 pb-3 screen-body-scroll-qde  h-screen&quot;]/div[@class=&quot;bg-white flex flex-col gap-3 p-5 rounded-xl&quot;]/div[@class=&quot;grid grid-cols-2 gap-5&quot;]/div[1]/div[@class=&quot;w-full h-full&quot;]/div[@class=&quot;border border-primary-ptext-500 rounded-xl p-5 flex flex-col gap-3 text-xs&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;flex justify-start h-32.5&quot;]/div[@class=&quot;flex gap-x-6 overflow-x-auto custom-kyc-doc-scroll&quot;]/div[@class=&quot;flex flex-col relative max-w-fit&quot;]/div[@class=&quot;flex flex-col items-center gap-1&quot;]/div[@class=&quot;w-25 h-25 flex items-center justify-center bg-primary-ptext-200 border border-primary-ptext-600 rounded-xl cursor-pointer&quot;]/span[@class=&quot;select-none&quot;]/img[1]</value>
      <webElementGuid>f2135c21-6c79-4fc0-90da-c2c557215553</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[2]/div[2]/div/div/div/div[3]/div[2]/div/div/div/div/span/img</value>
      <webElementGuid>a42fb280-d80e-4afa-9dc3-6c43981b226d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='add-file']</value>
      <webElementGuid>72346a11-fbb5-432f-b5a1-c5eac06d701f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/img</value>
      <webElementGuid>8bcca1c3-d9aa-467a-aa61-b77fbbbfe162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/Add-09ceabbe.svg' and @alt = 'add-file']</value>
      <webElementGuid>9e45be7f-d7c9-4b00-b975-000647c1f998</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
