<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Product_product</name>
   <tag></tag>
   <elementGuidId>24e3b8bb-7b0b-4be4-80e0-10c5c1689238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='product']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;product&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1488705d-7aea-441a-8f15-ae1f543717da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6139f054-d3da-46c8-8f1c-d02d0f00530d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product</value>
      <webElementGuid>98468fb6-f603-41f2-8885-4e6821ff2603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>971255f7-e4cd-415e-802f-d28dd7c8f95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>c044f2b0-7621-4a5b-8504-fbe86425d233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>232148c2-055b-4f30-9e94-8be4ababd67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f4bf0194-ef7f-409c-a77a-56e4837ced2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-autocomplete-input  text-left  !mr-0  !ml-0  !mt-0  !mb-0  text-xs  px-2  py  w-full   border   border-primary-gray-600  rounded-md  outline-none  bg-white  focus:bg-white  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-primary-gray-800  pl-6  h-6  rounded-r    </value>
      <webElementGuid>5b5695dc-6d1c-4ddf-b04d-e672c4b9c00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9a527b34-6922-4459-af71-bb8aeea6e641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_7&quot;)/input[@class=&quot;p-inputtext p-component p-autocomplete-input  text-left  !mr-0  !ml-0  !mt-0  !mb-0  text-xs  px-2  py  w-full   border   border-primary-gray-600  rounded-md  outline-none  bg-white  focus:bg-white  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-primary-gray-800  pl-6  h-6  rounded-r&quot;]</value>
      <webElementGuid>51944261-3ec5-4f34-94e9-4f82b1043f1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='product']</value>
      <webElementGuid>1f300abe-9879-4f36-b176-fca4b7782c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pr_id_7']/input</value>
      <webElementGuid>636ce7e2-a5fc-4107-8c8f-42ca9ff78046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>85971aee-d44d-4fb5-b97a-3fb118643fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'product']</value>
      <webElementGuid>322f829d-c273-4132-9c77-52cc0eabbe97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
