<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sales Agent_salesAgent</name>
   <tag></tag>
   <elementGuidId>bd5d56b9-9975-413b-b1b7-3032aa02e90a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='salesAgent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;salesAgent&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5de6b84a-4ff5-4f38-b8b9-b03c17e43aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77bf184c-242a-4f1a-8bca-e43e00d3238b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>salesAgent</value>
      <webElementGuid>d1a88e70-018d-43bc-942b-99467ffa23dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>79c26247-0528-4cc9-8410-0f01e8ebc69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>e7ab09aa-5ee3-4783-913f-1eed4343f330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>04bebe08-9ab3-46a6-8cf2-f0f619b9bd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e1e8f708-a7e6-47a9-b752-9ed4605d4f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-autocomplete-input  text-left  !mr-0  !ml-0  !mt-0  !mb-0  text-xs  px-2  py  w-full   border   border-primary-gray-600  rounded-md  outline-none  bg-white  focus:bg-white  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-primary-gray-800  pl-6  h-6      </value>
      <webElementGuid>fc34b88f-e693-4082-80cc-d25f540d5ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b24122ee-94c0-4dec-9b9a-72c40b1047d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_9&quot;)/input[@class=&quot;p-inputtext p-component p-autocomplete-input  text-left  !mr-0  !ml-0  !mt-0  !mb-0  text-xs  px-2  py  w-full   border   border-primary-gray-600  rounded-md  outline-none  bg-white  focus:bg-white  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-primary-gray-800  pl-6  h-6&quot;]</value>
      <webElementGuid>65c54157-0bf5-40c1-9c1f-1abfedad57f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='salesAgent']</value>
      <webElementGuid>f4a7bddb-f173-43fc-9eef-844b2c2ad10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pr_id_9']/input</value>
      <webElementGuid>bfc626d5-9a0e-4ec4-9109-95484bde3bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/input</value>
      <webElementGuid>49798abf-f717-4d18-b39f-545bc5e23581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'salesAgent']</value>
      <webElementGuid>190e9c27-62f2-43a5-9931-9bc60250d07d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
