<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Self-Owned</name>
   <tag></tag>
   <elementGuidId>b63ed762-95bd-4023-aa66-5a0ae9e909e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[3]/div[2]/div[2]/div[2]/div/div[4]/div/div/div[4]/div/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.p-dropdown-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a8a8cf40-5859-4a6d-adc6-c71ff803bf5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-item</value>
      <webElementGuid>8efe6b2f-8781-486e-8152-84bc980ff032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Self-Owned</value>
      <webElementGuid>00455ab2-007d-4895-9697-7002172c932e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9b4413e9-b63d-4f87-8cca-044b61e3193a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f4fbf97-a0fe-4e57-81e4-a475f05f29e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Self-Owned</value>
      <webElementGuid>92f8a438-f1f9-4174-880e-3340c71ab810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-full flex overflow-hidden bg-primary-sapphireBlue-100&quot;]/div[@class=&quot;bg-primary-sapphireBlue-100 max-w-328 m-auto flex-1 h-screen overflow-hidden p-3&quot;]/main[@class=&quot;overflow-auto&quot;]/div[1]/div[@class=&quot;flex flex-col gap-5 pb-3 screen-body-scroll-qde  h-screen&quot;]/div[@class=&quot;bg-white flex flex-col gap-3 p-5 rounded-xl&quot;]/div[@class=&quot;border border-primary-sapphireBlue-600  rounded-xl p-5 flex flex-col gap-3&quot;]/div[@class=&quot;grid grid-cols-4 gap-2&quot;]/div[@class=&quot;col-span-3&quot;]/div[@class=&quot;grid grid-cols-3 gap-2&quot;]/div[@class=&quot;col-span-1&quot;]/div[@class=&quot;group grid&quot;]/div[@class=&quot;p-dropdown p-component p-inputwrapper p-inputwrapper-focus  text-left  text-xs   px-2   !py-0.5  w-full   border   border-primary-errorColor  rounded-md  outline-none  bg-white  focus:bg-white  focus:border-primary-red-600  focus:border focus:border-opacity-40  hover:bg-white  hover:border-primary-red-800  text-primary-navy-800  placeholder-secondary-gray-500  h-6&quot;]/div[@class=&quot;p-dropdown-panel p-component border border-t-0 border-secondary-steelBlue-300 text-primary-ptext-1000 rounded-md bg-white text-xs shadow-autoCompletePanel text-left p-connected-overlay-enter-done&quot;]/div[@class=&quot;p-dropdown-items-wrapper&quot;]/ul[@class=&quot;p-dropdown-items&quot;]/li[@class=&quot;p-dropdown-item&quot;]</value>
      <webElementGuid>31ef041d-49b2-43a5-a769-579aad7ca215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[3]/div[2]/div[2]/div[2]/div/div[4]/div/div/div[4]/div/ul/li</value>
      <webElementGuid>b979847a-7161-4d5a-8734-446689978707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='empty'])[1]/following::li[1]</value>
      <webElementGuid>1a718180-c004-4ece-99af-8414082dc70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of Residential Address*'])[1]/following::li[1]</value>
      <webElementGuid>a5daded3-13a9-4c1f-b220-037607d6f1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rented'])[1]/preceding::li[1]</value>
      <webElementGuid>a28efc2c-410a-4c5b-9c7c-f50842099daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parental'])[1]/preceding::li[2]</value>
      <webElementGuid>c427cdc5-ca6f-4699-b1d3-5efa827c1901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Self-Owned']/parent::*</value>
      <webElementGuid>c8eaffd0-c67e-4a14-b648-2def23d95b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li</value>
      <webElementGuid>31229bb2-f5a5-4d29-94e6-a2a2b77e64fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Self-Owned' or . = 'Self-Owned')]</value>
      <webElementGuid>792778cc-ac9b-4bfe-a175-95e16dd7a05b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
