<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Upload</name>
   <tag></tag>
   <elementGuidId>cad87a51-343b-43be-81fb-5387f7043818</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[2]/div[2]/div/div/div/div[3]/div[2]/div/div/div/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#root > div.w-full.flex.overflow-hidden.bg-primary-sapphireBlue-100 > div.bg-primary-sapphireBlue-100.max-w-328.m-auto.flex-1.h-screen.overflow-hidden.p-3 > main > div > div.flex.flex-col.gap-5.pb-3.screen-body-scroll-qde.h-screen > div:nth-child(2) > div.grid.grid-cols-2.gap-5 > div > div > div > div.flex.flex-col.gap-2 > div.flex.justify-start.h-32\.5 > div > div > div.flex.flex-col.items-center.gap-1 > button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8588e95f-9ca8-44d5-b7a1-ddd72e508454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/Add-09ceabbe.svg</value>
      <webElementGuid>8d792146-a11c-4c61-abb6-01ee439df319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>add-file</value>
      <webElementGuid>c1768564-a8fe-4ea2-a5f1-6cbb1b0fd8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-full flex overflow-hidden bg-primary-sapphireBlue-100&quot;]/div[@class=&quot;bg-primary-sapphireBlue-100 max-w-328 m-auto flex-1 h-screen overflow-hidden p-3&quot;]/main[@class=&quot;overflow-auto&quot;]/div[1]/div[@class=&quot;flex flex-col gap-5 pb-3 screen-body-scroll-qde  h-screen&quot;]/div[@class=&quot;bg-white flex flex-col gap-3 p-5 rounded-xl&quot;]/div[@class=&quot;grid grid-cols-2 gap-5&quot;]/div[1]/div[@class=&quot;w-full h-full&quot;]/div[@class=&quot;border border-primary-ptext-500 rounded-xl p-5 flex flex-col gap-3 text-xs&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;flex justify-start h-32.5&quot;]/div[@class=&quot;flex gap-x-6 overflow-x-auto custom-kyc-doc-scroll&quot;]/div[@class=&quot;flex flex-col relative max-w-fit&quot;]/div[@class=&quot;flex flex-col items-center gap-1&quot;]/div[@class=&quot;w-25 h-25 flex items-center justify-center bg-primary-ptext-200 border border-primary-ptext-600 rounded-xl cursor-pointer&quot;]/span[@class=&quot;select-none&quot;]/img[1]</value>
      <webElementGuid>aba31d22-0f37-4c34-9acc-b6ef24951801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[2]/div[2]/div/div/div/div[3]/div[2]/div/div/div/div/span/img</value>
      <webElementGuid>e2dbb303-6ee8-4b49-b500-003a748c56d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='add-file']</value>
      <webElementGuid>09f54376-769d-419b-b047-5766a24e1b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/img</value>
      <webElementGuid>f2c97ed2-db52-4a38-af88-f585d657f35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/Add-09ceabbe.svg' and @alt = 'add-file']</value>
      <webElementGuid>24af484f-c6ed-4524-ba97-b920069d6f1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
