<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_empty</name>
   <tag></tag>
   <elementGuidId>897d9a00-932a-416d-8471-9ed02b664874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[3]/div[2]/div[2]/div[2]/div/div[4]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a49679fa-2a43-4f82-ac1c-b09b7aadf8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown p-component p-inputwrapper  text-left  text-xs   px-2   !py-0.5  w-full   border   border-secondary-gray-300  rounded-md  outline-none  bg-white  focus:bg-white  focus:border-semantic-informativeAccent  focus:border focus:border-opacity-40  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-secondary-gray-500  h-6      </value>
      <webElementGuid>8ca0aeb0-1757-4bb2-b52f-1cb579237986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>7b34953c-263a-4c55-a751-41fc56b5ebbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-full flex overflow-hidden bg-primary-sapphireBlue-100&quot;]/div[@class=&quot;bg-primary-sapphireBlue-100 max-w-328 m-auto flex-1 h-screen overflow-hidden p-3&quot;]/main[@class=&quot;overflow-auto&quot;]/div[1]/div[@class=&quot;flex flex-col gap-5 pb-3 screen-body-scroll-qde  h-screen&quot;]/div[@class=&quot;bg-white flex flex-col gap-3 p-5 rounded-xl&quot;]/div[@class=&quot;border border-primary-sapphireBlue-600  rounded-xl p-5 flex flex-col gap-3&quot;]/div[@class=&quot;grid grid-cols-4 gap-2&quot;]/div[@class=&quot;col-span-3&quot;]/div[@class=&quot;grid grid-cols-3 gap-2&quot;]/div[@class=&quot;col-span-1&quot;]/div[@class=&quot;group grid&quot;]/div[@class=&quot;p-dropdown p-component p-inputwrapper  text-left  text-xs   px-2   !py-0.5  w-full   border   border-secondary-gray-300  rounded-md  outline-none  bg-white  focus:bg-white  focus:border-semantic-informativeAccent  focus:border focus:border-opacity-40  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-secondary-gray-500  h-6&quot;]</value>
      <webElementGuid>2ba0a3a5-732f-49ab-8dd0-e71b9285f0ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[3]/div[2]/div[2]/div[2]/div/div[4]/div/div</value>
      <webElementGuid>e988ed4b-b075-45d9-b7b3-8ff242b5d449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of Residential Address*'])[1]/following::div[1]</value>
      <webElementGuid>42afd363-4271-4ca0-809d-9d627e0ab2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State*'])[1]/following::div[4]</value>
      <webElementGuid>79f179b0-d422-421b-b1f0-123b48587514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Longitude*'])[1]/preceding::div[5]</value>
      <webElementGuid>8b8a77e1-fa45-4b08-b1f2-aa4c3a715312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[4]/div/div</value>
      <webElementGuid>62f52343-69a0-43b1-80a4-c70cb882b26f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'empty' or . = 'empty')]</value>
      <webElementGuid>a85a0db1-f8bb-4905-a1c7-84c8b2b98e36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
