<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_KYC Documents_w-3.5 h-3.5</name>
   <tag></tag>
   <elementGuidId>575205db-a3ed-47f1-8dcd-94ecdad24c10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[2]/div[2]/div/div/div/div/div/div/button[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>464f9050-257c-4e79-97de-daa254f4f96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/Save-df37c142.svg</value>
      <webElementGuid>a67b819d-2b32-4cf9-bfb2-e34652fc4734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> w-3.5 h-3.5 </value>
      <webElementGuid>3407142f-6c6b-4528-bf92-2604af21051a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sahayya Logo</value>
      <webElementGuid>b62f088f-4403-4ae8-93d6-f4ee41b1548b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>588825be-6fb1-40ac-9a7f-070de543c4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-full flex overflow-hidden bg-primary-sapphireBlue-100&quot;]/div[@class=&quot;bg-primary-sapphireBlue-100 max-w-328 m-auto flex-1 h-screen overflow-hidden p-3&quot;]/main[@class=&quot;overflow-auto&quot;]/div[1]/div[@class=&quot;flex flex-col gap-5 pb-3 screen-body-scroll-qde  h-screen&quot;]/div[@class=&quot;bg-white flex flex-col gap-3 p-5 rounded-xl&quot;]/div[@class=&quot;grid grid-cols-2 gap-5&quot;]/div[1]/div[@class=&quot;w-full h-full&quot;]/div[@class=&quot;border border-primary-sapphireBlue-600 rounded-xl p-5 flex flex-col gap-3 text-xs&quot;]/div[@class=&quot;flex items-center justify-end&quot;]/div[@class=&quot;flex gap-3&quot;]/div[@class=&quot;flex gap-6&quot;]/button[@class=&quot;p-button p-component  select-none&quot;]/img[@class=&quot;w-3.5 h-3.5&quot;]</value>
      <webElementGuid>4dbc2aac-2047-4e65-b876-d64b71a3ea0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[2]/div[2]/div/div/div/div/div/div/button[2]/img</value>
      <webElementGuid>58a96414-b843-4001-810d-a46c1b6e322a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Sahayya Logo'])[4]</value>
      <webElementGuid>b8962dff-ee56-47bb-96c6-bc764cb753e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/button[2]/img</value>
      <webElementGuid>c4857a7d-996c-4598-a879-d62efeef956a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/Save-df37c142.svg' and @alt = 'Sahayya Logo']</value>
      <webElementGuid>a1546c64-751d-4bb9-8337-586dc088e5c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
