<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pincode_pincode</name>
   <tag></tag>
   <elementGuidId>28ee9911-dcd8-4fd2-a93f-6429f7a394a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pincode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pincode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a36588b0-7140-41b5-844d-79caa290f0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f9fd5d4-9223-4025-a17e-86291ecbdab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pincode</value>
      <webElementGuid>65bbddd6-6d2c-4209-811a-f87bb6bb801b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>ec019418-65ac-4382-bec9-ed6a37588353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>4a6d4592-1acf-4912-b035-5a4d2e4e2be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>8152be02-e29f-4a47-8079-7400a3c6391d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b0d29b52-9f47-4bd6-acf2-615fbfd15194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-autocomplete-input  text-left  !mr-0  !ml-0  !mt-0  !mb-0  text-xs  px-2  py  w-full   border   border-primary-gray-600  rounded-md  outline-none  bg-white  focus:bg-white  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-primary-gray-800  pl-6  h-6      </value>
      <webElementGuid>1584b1a3-2148-4d6a-ac2c-4352567e6781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e39df5b1-b337-4e9e-88a8-70d862aba6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_17&quot;)/input[@class=&quot;p-inputtext p-component p-autocomplete-input  text-left  !mr-0  !ml-0  !mt-0  !mb-0  text-xs  px-2  py  w-full   border   border-primary-gray-600  rounded-md  outline-none  bg-white  focus:bg-white  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-primary-gray-800  pl-6  h-6&quot;]</value>
      <webElementGuid>e0d120fa-b998-4f95-8a3e-d15372ffcf81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pincode']</value>
      <webElementGuid>c07f0d34-66ea-4d9b-986a-f90ae11022ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pr_id_17']/input</value>
      <webElementGuid>8b89bf81-9139-4d3f-abeb-fa41e980a2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>7aef9f9b-2b9f-4e9d-b403-b2ece009b5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pincode']</value>
      <webElementGuid>a4cd0a0e-bf69-4380-ba53-fb0d45671918</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
