<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__panNo</name>
   <tag></tag>
   <elementGuidId>a5a024ba-7f71-4f90-93e7-09df9beda724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='panNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;panNo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d0633c4-30a7-4089-8d10-576b1375fb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>panNo</value>
      <webElementGuid>a2f60574-7e3e-418b-80f3-182a98ff1ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component  text-left  text-xs  px-2  py-2  w-full   border   border-secondary-gray-300  rounded-md  outline-none  bg-white  focus:bg-white  focus:border-semantic-informativeAccent  focus:border focus:border-opacity-40  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-secondary-gray-500  h-9  !h-6 !py-1 !px-2 focus:outline-0 !focus:border focus:border-secondary-steelBlue-300 outline-0    </value>
      <webElementGuid>64af4ba5-93b8-4fcd-80e5-661a8c8ff02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-full flex overflow-hidden bg-primary-sapphireBlue-100&quot;]/div[@class=&quot;bg-primary-sapphireBlue-100 max-w-328 m-auto flex-1 h-screen overflow-hidden p-3&quot;]/main[@class=&quot;overflow-auto&quot;]/div[1]/div[@class=&quot;flex flex-col gap-5 pb-3 screen-body-scroll-qde  h-screen&quot;]/div[@class=&quot;bg-white flex flex-col gap-3 p-5 rounded-xl&quot;]/div[@class=&quot;grid grid-cols-2 gap-5&quot;]/div[1]/div[@class=&quot;w-full h-full&quot;]/div[@class=&quot;border border-primary-sapphireBlue-600 rounded-xl p-5 flex flex-col gap-3 text-xs&quot;]/div[@class=&quot;-mx-5 px-5 pt-3 border-t-0.5  border-primary-sapphireBlue-600&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;flex flex-wrap items-center justify-between&quot;]/div[1]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;w-50&quot;]/div[@class=&quot;group grid w-full&quot;]/input[@class=&quot;p-inputtext p-component  text-left  text-xs  px-2  py-2  w-full   border   border-secondary-gray-300  rounded-md  outline-none  bg-white  focus:bg-white  focus:border-semantic-informativeAccent  focus:border focus:border-opacity-40  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-secondary-gray-500  h-9  !h-6 !py-1 !px-2 focus:outline-0 !focus:border focus:border-secondary-steelBlue-300 outline-0&quot;]</value>
      <webElementGuid>5983db6c-e632-41ad-8c51-294d8504231b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='panNo']</value>
      <webElementGuid>1f03800f-fda1-43dc-ad75-ec501b8f21bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[2]/div[2]/div/div/div/div[4]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>8c3b56e0-c4b4-47ac-8c7d-6474d72797d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>3ea95911-42db-479c-8883-341999899ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'panNo']</value>
      <webElementGuid>ab5b1680-33ee-4034-af55-329c7f31145f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
