<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_560025</name>
   <tag></tag>
   <elementGuidId>1ab7cbd6-dd07-4bec-b3eb-5fd05ce94a91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div[2]/main/div/div[2]/div[3]/div[2]/div[2]/div[2]/div/div[1]/div/div[1]/span/div/ul/li[1]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5fa71940-d292-48db-b348-7749eb64d7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> text-primary-labelColor</value>
      <webElementGuid>d2f8cc2b-ba86-423b-b431-d81372029ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>560025</value>
      <webElementGuid>1ffcc711-b0c6-4e11-b1a1-73d11341cdcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_17_list&quot;)/li[@class=&quot;p-autocomplete-item&quot;]/div[@class=&quot;flex flex-col&quot;]/label[@class=&quot;text-primary-labelColor&quot;]</value>
      <webElementGuid>ea0032f9-4484-471f-ac7a-4a201832016d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_17_list']/li/div/label</value>
      <webElementGuid>a983e2bb-f8a8-4c7e-9afb-70aa2b5dc86b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pincode*'])[1]/following::label[1]</value>
      <webElementGuid>451c2917-ea95-4e08-bb63-f9f84a0b083f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address*'])[1]/following::label[2]</value>
      <webElementGuid>c959db24-a589-4d1a-b90d-cf8a91ad48c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mandatory'])[1]/preceding::label[1]</value>
      <webElementGuid>10d1783a-299e-4364-b888-fcaac28fad72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City*'])[1]/preceding::label[2]</value>
      <webElementGuid>b7bc83e9-cd46-47b6-811b-b7c343c5eb38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='560025']/parent::*</value>
      <webElementGuid>4dda2705-23ee-40f7-b5d5-82e54aa8b3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/label</value>
      <webElementGuid>b1b71519-f314-4e41-be18-816afdb8334f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '560025' or . = '560025')]</value>
      <webElementGuid>67034138-da85-4cfd-941a-b0cebbb7cd99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
