<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Profile Pic Upload</name>
   <tag></tag>
   <elementGuidId>1fad209b-f50a-48ce-bb38-dcadb0044d38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>*[@id=&quot;root&quot;]/div[3]/div[2]/main/div/div[2]/div[3]/div[1]/div[2]/div[2]/div[1]/div/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;save&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2e3621e1-2dfc-4048-87f5-6a7888001185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/Save_Image-8e728893.svg</value>
      <webElementGuid>682f0df0-0a53-4043-938f-b320f8d1e2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>8a38f258-c4ba-4388-b406-7caebc57c355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_83_content&quot;)/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;self-center py-3 flex gap-5&quot;]/div[@class=&quot;flex flex-col text-xs items-center justify-center&quot;]/button[@class=&quot;w-12 h-12 cursor-pointer&quot;]/img[1]</value>
      <webElementGuid>7e8bdcda-9967-459f-812b-5cdcee7f4ed2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_83_content']/div/div[4]/div[2]/button/img</value>
      <webElementGuid>b49ca156-4dfe-4969-bed9-13c3d995c2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='save']</value>
      <webElementGuid>7c6a6dfb-a0fb-4eed-b9e3-bb3f3e4502ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/img</value>
      <webElementGuid>eff4fcc6-d14c-4872-9ede-8b66fdd19014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/Save_Image-8e728893.svg' and @alt = 'save']</value>
      <webElementGuid>625a0028-683d-40a2-be7a-c0e5176a1e82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
