<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_empty_p-dropdown-trigger-icon p-clicka_bedf43_1_2</name>
   <tag></tag>
   <elementGuidId>464287d0-8280-433c-b4f8-6032b3cbbe9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[3]/div/div[4]/div[2]/div/div/div/div/div/div[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6e578878-24f8-4933-b1f3-c0de5ea1e042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-trigger-icon p-clickable pi pi-chevron-down</value>
      <webElementGuid>ec16cefc-fbc4-43dc-afad-8121e3c6f66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-full flex overflow-hidden bg-primary-sapphireBlue-100&quot;]/div[@class=&quot;bg-primary-sapphireBlue-100 max-w-328 m-auto flex-1 h-screen overflow-hidden p-3&quot;]/main[@class=&quot;overflow-auto&quot;]/div[1]/div[@class=&quot;flex flex-col gap-5 pb-3 screen-body-scroll-qde  h-screen&quot;]/div[@class=&quot;bg-white flex flex-col gap-3 p-5 rounded-xl&quot;]/div[@class=&quot;border border-primary-sapphireBlue-600  rounded-xl p-5 flex flex-col gap-3&quot;]/div[@class=&quot;flex flex-col gap-3&quot;]/div[@class=&quot;doc-uploader&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;w-full flex items-center justify-between&quot;]/div[@class=&quot;w-61&quot;]/div[@class=&quot;group grid&quot;]/div[@class=&quot;p-dropdown p-component p-inputwrapper  text-left  text-xs   px-2   !py-0.5  w-full   border   border-secondary-gray-300  rounded-md  outline-none  bg-white  focus:bg-white  focus:border-semantic-informativeAccent  focus:border focus:border-opacity-40  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-secondary-gray-500  h-6&quot;]/div[@class=&quot;p-dropdown-trigger&quot;]/span[@class=&quot;p-dropdown-trigger-icon p-clickable pi pi-chevron-down&quot;]</value>
      <webElementGuid>f33ea0b8-c70b-4f1d-b844-5a1d6a52dda7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[3]/div/div[4]/div[2]/div/div/div/div/div/div[3]/span</value>
      <webElementGuid>b8c4c199-4f71-4a45-8883-6e36251f9e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div/div/div[3]/span</value>
      <webElementGuid>86fd9de2-cedc-4f9e-b39f-a1043d2b2858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
