<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sep</name>
   <tag></tag>
   <elementGuidId>b725b47a-aaa8-4ac7-8326-e843ab4fed1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Aug'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f6ae5acd-b028-4e89-b134-1de6a91aaded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-monthpicker-month</value>
      <webElementGuid>424a6953-82d5-428e-9cad-b09d96b352c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sep</value>
      <webElementGuid>c1848f24-051a-4198-8b3c-7492f19a4034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;p-datepicker p-component border p-2 rounded-lg  border-inputBorderColor bg-white text-inputTextColor p-datepicker-monthpicker&quot;]/div[@class=&quot;p-monthpicker&quot;]/span[@class=&quot;p-monthpicker-month&quot;]</value>
      <webElementGuid>4f0f3fbf-1644-470e-9206-050f3f4c40a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aug'])[1]/following::span[1]</value>
      <webElementGuid>0c5e26a7-35cc-4bdb-838b-d012d312fb13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jul'])[1]/following::span[2]</value>
      <webElementGuid>14c12696-b08c-475d-a273-5c61c8384dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oct'])[1]/preceding::span[1]</value>
      <webElementGuid>d7ba51ca-7e9b-4b79-baf1-6be123b56178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nov'])[1]/preceding::span[2]</value>
      <webElementGuid>a9fa3d86-210b-48fd-85cf-e4ebb582e519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sep']/parent::*</value>
      <webElementGuid>394c5f76-c4c7-4faf-9509-409561bb2c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[9]</value>
      <webElementGuid>8be33dc1-c042-4581-b33c-aeca131b8136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sep' or . = 'Sep')]</value>
      <webElementGuid>39c3dc77-8f9a-49ca-bf21-557845b56e29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
