<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address proof dropdown</name>
   <tag></tag>
   <elementGuidId>5c145aaa-404b-4b6b-8824-fab6cc7bb6d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[3]/div[2]/div[5]/div[2]/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9c508ee-dfde-40f8-aa4d-dcf651d34c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown p-component p-inputwrapper  text-left  text-xs   px-2   !py-0.5  w-full   border   border-primary-errorColor  rounded-md  outline-none  bg-white  focus:bg-white  focus:border-primary-red-600  focus:border focus:border-opacity-40  hover:bg-white  hover:border-primary-red-800  text-primary-navy-800  placeholder-secondary-gray-500  h-6      </value>
      <webElementGuid>d97d95cf-56bc-458a-9055-04f45ec4423b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>74b5a6b8-2a39-48c0-9be8-149b9a56408d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-full flex overflow-hidden bg-primary-sapphireBlue-100&quot;]/div[@class=&quot;bg-primary-sapphireBlue-100 max-w-328 m-auto flex-1 h-screen overflow-hidden p-3&quot;]/main[@class=&quot;overflow-auto&quot;]/div[1]/div[@class=&quot;flex flex-col gap-5 pb-3 screen-body-scroll-qde  h-screen&quot;]/div[@class=&quot;bg-white flex flex-col gap-3 p-5 rounded-xl&quot;]/div[@class=&quot;border border-primary-sapphireBlue-600  rounded-xl p-5 flex flex-col gap-3&quot;]/div[@class=&quot;flex flex-col gap-3&quot;]/div[@class=&quot;doc-uploader&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;w-full flex items-center justify-between&quot;]/div[@class=&quot;w-61&quot;]/div[@class=&quot;group grid&quot;]/div[@class=&quot;p-dropdown p-component p-inputwrapper  text-left  text-xs   px-2   !py-0.5  w-full   border   border-primary-errorColor  rounded-md  outline-none  bg-white  focus:bg-white  focus:border-primary-red-600  focus:border focus:border-opacity-40  hover:bg-white  hover:border-primary-red-800  text-primary-navy-800  placeholder-secondary-gray-500  h-6&quot;]</value>
      <webElementGuid>a4462376-6442-4bd5-a2ab-1ca439c63679</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[3]/div[2]/div[5]/div[2]/div/div/div/div/div</value>
      <webElementGuid>6dd5cefd-9a3a-418c-8e5e-cc37a8885226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Proof *'])[1]/following::div[6]</value>
      <webElementGuid>62b4081c-0f52-45a3-9125-08659feb04a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mark Using Map'])[1]/following::div[10]</value>
      <webElementGuid>14cd4565-2de8-4c02-acf1-a1f787e0d0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mandatory'])[5]/preceding::div[4]</value>
      <webElementGuid>d66650ab-899d-4a45-9d73-d6d6322c2d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div/div</value>
      <webElementGuid>f8157ca0-c6eb-4d09-88ac-d822b759e01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'empty' or . = 'empty')]</value>
      <webElementGuid>ccbbbaec-90a3-4102-aa28-35aafcc0e5a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
