<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img SAVE</name>
   <tag></tag>
   <elementGuidId>2917b8df-53b0-437f-999b-939191a808e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_83_content']/div/div[4]/div[2]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;save&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>78840770-bd2d-4542-a6ec-79526fbe471d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/Save_Image-8e728893.svg</value>
      <webElementGuid>700745c1-3982-4ef0-8e3d-6f49400423cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>bf37f420-8fea-493b-8f53-4ff65e216941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_83_content&quot;)/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;self-center py-3 flex gap-5&quot;]/div[@class=&quot;flex flex-col text-xs items-center justify-center&quot;]/button[@class=&quot;w-12 h-12 cursor-pointer&quot;]/img[1]</value>
      <webElementGuid>4e57dc7a-6373-45d2-9a09-9f7025e8768b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_83_content']/div/div[4]/div[2]/button/img</value>
      <webElementGuid>cd83d103-8a86-47bc-9520-56fe2c83572d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='save']</value>
      <webElementGuid>aadfc434-311e-464c-a4fb-ae4cf8df9d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/img</value>
      <webElementGuid>4e5bf398-4b7f-4819-9d66-a543fa77200d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/Save_Image-8e728893.svg' and @alt = 'save']</value>
      <webElementGuid>d134bf95-c2bc-4cd6-a88a-6d79690c6be8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
