<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>731a717c-dfb8-4132-835e-018a48c4dbf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div[3]/div[2]/main/div/div[2]/div[3]/div[1]/div[2]/div[2]/div[1]/div/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#root > div.w-full.flex.overflow-hidden.bg-primary-sapphireBlue-100 > div.bg-primary-sapphireBlue-100.max-w-328.m-auto.flex-1.h-screen.overflow-hidden.p-3 > main > div > div.flex.flex-col.gap-5.pb-3.screen-body-scroll-qde.h-screen > div:nth-child(2) > div.grid.grid-cols-2.gap-5 > div > div > div > div.flex.flex-col.gap-2 > div.flex.justify-start.h-32\.5 > div > div > div.flex.flex-col.items-center.gap-1 > button > span > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>72fc11d8-0aee-4fef-9cf3-ad75a94b6a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/Add-09ceabbe.svg</value>
      <webElementGuid>142c8466-4faf-4ef7-8098-b53ecb1bef56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>add-file</value>
      <webElementGuid>35f0b1e7-5de3-437f-b8f8-c37e5c7d345f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-full flex overflow-hidden bg-primary-sapphireBlue-100&quot;]/div[@class=&quot;bg-primary-sapphireBlue-100 max-w-328 m-auto flex-1 h-screen overflow-hidden p-3&quot;]/main[@class=&quot;overflow-auto&quot;]/div[1]/div[@class=&quot;flex flex-col gap-5 pb-3 screen-body-scroll-qde  h-screen&quot;]/div[@class=&quot;bg-white flex flex-col gap-3 p-5 rounded-xl&quot;]/div[@class=&quot;grid grid-cols-2 gap-5&quot;]/div[1]/div[@class=&quot;w-full h-full&quot;]/div[@class=&quot;border border-primary-sapphireBlue-600 rounded-xl p-5 flex flex-col gap-3 text-xs&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;flex justify-start h-32.5&quot;]/div[@class=&quot;flex gap-x-6 overflow-x-auto custom-kyc-doc-scroll&quot;]/div[@class=&quot;flex flex-col relative max-w-fit&quot;]/div[@class=&quot;flex flex-col items-center gap-1&quot;]/button[@class=&quot;w-25 h-25 flex items-center justify-center bg-primary-ptext-200 border border-primary-ptext-600 rounded-xl cursor-pointer&quot;]/span[@class=&quot;select-none&quot;]/img[1]</value>
      <webElementGuid>3e411070-3846-4615-9156-a78deb4d89d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/main/div/div[2]/div[2]/div[2]/div/div/div/div[3]/div[2]/div/div/div/button/span/img</value>
      <webElementGuid>2d9a2c59-9da6-4d22-a5da-5ebefc27031d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='add-file']</value>
      <webElementGuid>fcc5306c-c36f-4370-9133-7a84095c40b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button/span/img</value>
      <webElementGuid>1f86fbfc-db8f-43d3-9edb-451b88d2d68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/Add-09ceabbe.svg' and @alt = 'add-file']</value>
      <webElementGuid>643d94d8-32ae-4369-bcc5-ae917e1f62b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
