<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pincode_pincode</name>
   <tag></tag>
   <elementGuidId>87c84c96-c82e-4ade-b532-6d3c2a7be85c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pincode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pincode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>353f621f-687c-43ce-9230-6c325f734287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>96dddd0d-1de6-4003-baf2-48e03cb4fdc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pincode</value>
      <webElementGuid>e2d4b489-eb6b-429d-a2bc-39760dad8343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>3757f281-817a-423c-9e70-6c5c283be3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>1b782a28-b357-4d58-9319-c1f350728106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>25077142-ef52-4dc8-b34b-5ef4e998205b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8a4b1722-d6b6-4b86-bd84-a9f9ee3a93d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-autocomplete-input  text-left  !mr-0  !ml-0  !mt-0  !mb-0  text-xs  px-2  py  w-full   border   border-primary-gray-600  rounded-md  outline-none  bg-white  focus:bg-white  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-primary-gray-800  pl-6  h-6      </value>
      <webElementGuid>e8e13246-95bf-4fe6-a5a1-e1fb77f6a51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c32f1a1f-628b-4e10-9f95-1207d8950bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_15&quot;)/input[@class=&quot;p-inputtext p-component p-autocomplete-input  text-left  !mr-0  !ml-0  !mt-0  !mb-0  text-xs  px-2  py  w-full   border   border-primary-gray-600  rounded-md  outline-none  bg-white  focus:bg-white  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-primary-gray-800  pl-6  h-6&quot;]</value>
      <webElementGuid>f9b901e7-e504-46ef-b4ec-9575e7db7d5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pincode']</value>
      <webElementGuid>e7ecd731-8ac4-40e9-93c7-e777eab4d5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pr_id_15']/input</value>
      <webElementGuid>123bc736-7c1b-4288-929b-c374a9c6c061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>e0724ac0-7def-4a82-bea8-ad033bdcd6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pincode']</value>
      <webElementGuid>d1a4c373-254c-467d-863f-ba4e5068bbf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
