<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_city</name>
   <tag></tag>
   <elementGuidId>e9d0e435-70e3-4107-b753-cd230bc36035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;city&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed145bb4-65b9-414e-bbee-136cf6f7851f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ec12ff6-b6bb-4e5e-91c8-9dd9270358f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>a1a8b8d9-ca57-4ff4-a81f-2d1bda18b72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>43e2071f-f928-40e5-86db-e13055c10b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>16b630ee-5944-49b9-9a6e-9c40fc19cc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>98b22808-dffe-4de8-bf1f-a4c55925c7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e9b859c2-ecbd-49ae-960c-2c2695cca230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-autocomplete-input  text-left  !mr-0  !ml-0  !mt-0  !mb-0  text-xs  px-2  py  w-full   border   border-primary-gray-600  rounded-md  outline-none  bg-white  focus:bg-white  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-primary-gray-800  pl-6  h-6      </value>
      <webElementGuid>278c8237-2ccc-4097-a1c6-c8406e2b86b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2b1d2140-9186-405b-936e-7dbd69668b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_16&quot;)/input[@class=&quot;p-inputtext p-component p-autocomplete-input  text-left  !mr-0  !ml-0  !mt-0  !mb-0  text-xs  px-2  py  w-full   border   border-primary-gray-600  rounded-md  outline-none  bg-white  focus:bg-white  hover:bg-white  hover:border-primary-sapphireBlue-600  text-primary-ptext-1000  placeholder-primary-gray-800  pl-6  h-6&quot;]</value>
      <webElementGuid>656c3301-fde9-41d9-bc97-194da375ec8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='city']</value>
      <webElementGuid>ac3fb3df-47dd-4559-8e33-fd295987ae24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='pr_id_16']/input</value>
      <webElementGuid>654e6e4e-0e38-4128-a96c-aaaa63566fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/span/input</value>
      <webElementGuid>98344110-0507-4bf7-b143-14b824d6a2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'city']</value>
      <webElementGuid>a1c4ea42-f203-49e1-a0ac-a56c3bb491bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
